name: "default_workflow"

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    name: "step1"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # This is the PAT, GITHUB_TOKEN didn't work for submodules.
          # token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          # token: ${{env.PERSONAL_ACCESS_TOKEN}}
          fetch-depth: 0
          submodules: recursive
      - name: "step1.1"
        run: | 
          mkdir -p /${{github.workspace}}/out
          touch /${{github.workspace}}/out/progress
          echo "job1:steps:run" | tee -a /${{github.workspace}}/out/progress
  
  job2:
    runs-on: ubuntu-latest
    name: "step2"
    steps:
      - run: echo "job2:steps:run" | tee -a /${{github.workspace}}/out/progress
      - run: cat  /${{github.workspace}}/out/progress
