name: "default_workflow"

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: self-hosted-pop-sree
    name: "step1"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: "step1.1"
        run: | 
          mkdir -p /${{github.workspace}}/out
          touch /${{github.workspace}}/out/progress
          echo "job1:steps:run" | tee -a /${{github.workspace}}/out/progress
          pwd && ls -l
          echo "TEST_EXP: $TEST_EXP"
          chmod +x ./test_script.sh
          ./test_script.sh
          source ./values.sh
          echo "TEST_EXP: $TEST_EXP"
      - name: "store artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: output-files
          path: /${{github.workspace}}/out/progress
  
  job2:
    runs-on: ubuntu-latest
    name: "step2"
    needs: job1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: "download artifacts"
        uses: actions/download-artifact@v3
        with:
          name: output-files
          path: /${{github.workspace}}/out/
      - name: "second job2/step"
        run: |
          pwd && ls -lR
          echo "job2:steps:run" | tee -a /${{github.workspace}}/out/progress
          cat  /${{github.workspace}}/out/progress
